### ISSUE TITLE
run train.py 的时候报错:casting strings to float is not supported

### ISSUE THREAD

**Issue by SitengKang** [A-bone1/Attention-ocr-Chinese-Version#15]
您好！具体的error message如下：
UnimplementedError (see above for traceback): Cast string to float is not supported
	 [[Node: Momentum/update_AttentionOcr_v1/conv_tower_fn/INCE/InceptionV3/Conv2d_1a_3x3/weights/Cast_1 = Cast[DstT=DT_FLOAT, SrcT=DT_STRING, _class=["loc:@AttentionOcr_v1/conv_tower_fn/INCE/InceptionV3/Conv2d_1a_3x3/weights"], _device="/job:localhost/replica:0/task:0/device:CPU:0"](Momentum/momentum)]]

问题出在这一句上
clip_gradient_norm=FLAGS.clip_gradient_norm
 一开始怀疑是我生成dict的时候出了问题， 后再换上了原来的dict和tfrecod_example 还是报一样的错。 请问有人遇到过这种情况吗？

谢谢

**Comment by richielo** [comment]
Hello, @stankang96. I am encountering the same error, may I ask how did you solve it?

**Comment by SitengKang** [comment]
Hi @richielo, I solved this problem by changing one line in the common_flags.py:
from 
flags.DEFINE_**string**('momentum', 0.9,
                      'momentum value for the momentum optimizer if used')
to
flags.DEFINE_**float**('momentum', 0.9,
                      'momentum value for the momentum optimizer if used')
