### ISSUE TITLE
gtx 1080ti 下OOM

### ISSUE THREAD

**Issue by mymynew** [A-bone1/Attention-ocr-Chinese-Version#17]
问下这份代码是在什么gpu下训练的？
为什么1080ti 批次改到1都内存不够~

**Comment by A-bone1** [comment]
@mymynew 你好，我当时也是1080显示显存不足，建议可以调小图片的尺寸。

**Comment by mymynew** [comment]
图片的大小调整，你的是多少，有参考值吗？

**Comment by A-bone1** [comment]
@mymynew  我当时直接用cpu进行训练了

**Comment by mymynew** [comment]
经过我的测试
字符集按1000、2500、3000、4000、5000
批次按32、16、8设置
在1080ti下：
1000、2500字符集，批次支持到32，不会显存溢出
3000字符集，批次支持到16
4000字符集，批次支持到8
5000字符集，批次支持到4，但是图片大小必须调整，否则OOM。
另5000字符集，在 Tesla P100下可以不调整图片支持批次32.
重点看来需要关注下中文常用字的字符集数量~还没仔细测试5000字符该多大图片，而不影响效果
