### ISSUE TITLE
训练时cpu占满死机

### ISSUE THREAD

**Issue by MorningMyFriend** [A-bone1/Attention-ocr-Chinese-Version#28]
大家好，请问大家都是用cpu训练的吗？我的cpu是16g, i7-7700HQ，训练的时候内存和使用率都满了，然后就死机了，batch-size降低到1也没有作用。请问大家是如何用cpu训练的呢？

**Comment by MorningMyFriend** [comment]
发现有个线程使用数量调小就可以了

**Comment by mayidu** [comment]
你好，请问一下，你说的线程使用数量，在哪儿调呢，谢谢
