### ISSUE TITLE
测试结果有误

### ISSUE THREAD

**Issue by zhuliqian** [A-bone1/Attention-ocr-Chinese-Version#31]
INFO 2018-09-03 15:52:55.000546: tf_logging.py: 82 Restoring parameters from model.ckpt-834456
b'\xe7\xbc\xba\xe7\xbc\xba\xe7\xbc\xba\xe7\xbc\xba\xe7\xbc\xba\xe7\xbc\xba\xe7\xbc\xba\xe7\xbc\xba\xe7\xbc\xba\xe7\xbc\xba\xe7\xbc\xba\xe7\xbc\xba\xe7\xbc\xba\xe7\xbc\xba\xe7\xbc\xba'
b'\xe7\xbc\xba\xe7\xbc\xba\xe7\xbc\xba\xe7\xbc\xba\xe7\xbc\xba\xe7\xbc\xba\xe7\xbc\xba\xe7\xbc\xba\xe7\xbc\xba\xe7\xbc\xba\xe7\xbc\xba\xe7\xbc\xba\xe7\xbc\xba\xe7\xbc\xba\xe7\xbc\xba'

**Comment by A-bone1** [comment]
you can use  print( "********".decode('utf-8')) by python2

**Comment by zhuliqian** [comment]
thanks

**Comment by zzhaohao** [comment]
@A-bone1 您好，请问我在python3.5环境下也出现这样的问题该如何解决？谢谢！

**Comment by A-bone1** [comment]
@zzhaohao 这应该是编解码的问题，可以查查相关资料。你也可以使用python2先试一下结果正确性 print( "********".decode('utf-8'))
