### ISSUE TITLE
训练时预测结果正常，测试时结果不正常

### ISSUE THREAD

**Issue by richlaji** [A-bone1/Attention-ocr-Chinese-Version#34]
你好，我在train.py的时候查看tensorboard，预测结果和真实值接近，较正常。但是同一个模型在demo_inference.py和eval.py时预测结果则和真实值相差较大，请问你有遇到类似的情况嘛~期待解答

**Comment by richlaji** [comment]
![img20181030_112112](https://user-images.githubusercontent.com/10303294/47693786-f7964d00-dc35-11e8-8fb2-7342b5da4058.png)
![img20181030_112129](https://user-images.githubusercontent.com/10303294/47693787-f7964d00-dc35-11e8-8359-a21dd48ea961.png)
上图是tensorboard中eval和train的结果，train的预测有不同 ，但是test是完全一样~

**Comment by A-bone1** [comment]
@richlaji 你好，在train上的预测和在test上预测的是同一类的图片吗，你可以尝试着将训练集的图片利用demo_inference.py和eval.py时预测下结果，如果结果没有较为正常，可能是测试数据出了问题，如果预测同样不正常，可能是demo_inference.py和eval.py中的加载模型或预测的代码有问题。

**Comment by richlaji** [comment]
感谢回复，我试过demo_inference也是不正常，之前那张图就是用eval的也是不正常。代码部分我没有修改，我试了两次，重新download再训练也是不正常的结果~

**Comment by Lanme** [comment]
> 感谢回复，我试过demo_inference也是不正常，之前那张图就是用eval的也是不正常。代码部分我没有修改，我试了两次，重新download再训练也是不正常的结果~

请问你是怎么解决的？

**Comment by wenston2006** [comment]
同问, 问题如何解决的?
