### ISSUE TITLE
GPU 训练问题

### ISSUE THREAD

**Issue by ElagJun** [A-bone1/Attention-ocr-Chinese-Version#4]
我使用GPU 训练一直报`2018-04-20 14:26:01.064535: W tensorflow/core/framework/op_kernel.cc:1158] Resource exhausted: OOM when allocating tensor with shape[5751,5463]
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.ResourceExhaustedError'>, OOM when allocating tensor with shape[16,1152,1,288]
`
更改batch_size 也不管用，请问这个如何解决呢

最后调到batch_size = 2 才能训练。。这么占内存吗

**Comment by A-bone1** [comment]
这个问题说明显存不够。这个模型十分占内存，我使用GTX1080 11G的显存也爆了

**Comment by A-bone1** [comment]
建议可以把图片尺寸调小一点

**Comment by ElagJun** [comment]
两块titan 也费劲...




| |
邮箱：elag_1988@163.com
|

签名由 网易邮箱大师 定制

在2018年04月23日 00:30，A-bone1 写道：

建议可以把图片尺寸调小一点

**Comment by ElagJun** [comment]
请问需要改哪几个地方

**Comment by A-bone1** [comment]
@ElagJun  在生成FSNS格式的tf_record时在FSNS-tfrecord-generate.py里将img.resize里的值改一下，然后在/python/datasets/newtextdataset.py中，将图片尺寸改成和生成tfrecords时一样就可以了

**Comment by ElagJun** [comment]
@A-bone1  万分感谢 可以了
