### ISSUE TITLE
训练的时候会出现killed,然后就停了

### ISSUE THREAD

**Issue by zhuliqian** [A-bone1/Attention-ocr-Chinese-Version#40]
247 (3.054 sec/step)
INFO:tensorflow:Saving checkpoint to path /home/chase/Downloads/Attention-ocr-Chinese-Version-master/python/logs/model.ckpt
INFO 2019-01-01 18:11:04.000964: tf_logging.py: 82 Saving checkpoint to path /home/chase/Downloads/Attention-ocr-Chinese-Version-master/python/logs/model.ckpt
Killed

**Comment by mayidu** [comment]
你好，请问你这个问题解决了吗，我也遇到同样的问题！

**Comment by zhuliqian** [comment]
@mayidu 我把图片大小缩小了一半，就可以了，可能是内存什么的原因？我也不知道

**Comment by mayidu** [comment]
你现在训练出来了吗？你用的数据，是作者提供的数据吗？我也试一试

**Comment by zhuliqian** [comment]
作者有提供数据吗我没看到，我按照他提供的方法走了一遍，可以训练，数据是根据网上的代码自己生成的。倒也能识别，不过结果最后有一些llll字符，不知道为什么

**Comment by mayidu** [comment]
你是用的什么训练集呢，是360万的那个吗，怎么根据网上的代码生成的，能否给我发一下链接啊，谢谢

**Comment by zhuliqian** [comment]
https://github.com/Belval/TextRecognitionDataGenerator
我生成了五万张，就是想试一下能不能跑通，想要效果好可能需要更多的数据集吧

**Comment by mayidu** [comment]
好的，万分感谢，我也跑一下试试。
再问一下，你是在CPU还是GPU上训练的，大概需要多长时间，占内存跟显存怎么样呢？

**Comment by zhuliqian** [comment]
GPU，十来个小时吧，内存显存的不清楚

**Comment by mayidu** [comment]
好的，特别感谢，我试试，谢谢啦
