### ISSUE TITLE
预测问题

### ISSUE THREAD

**Issue by ElagJun** [A-bone1/Attention-ocr-Chinese-Version#5]
在我预测的时候只能预测出最后一个字符，其他的字符都预测不出来，
`Reading C:\Elag\data\cn_ocr\train\31c768fe-444d-11e8-9e87-005056bed121.jpg
INFO:tensorflow:Graph was finalized.
INFO 2018-04-24 09:37:51.000062: tf_logging.py: 116 Graph was finalized.
INFO:tensorflow:Restoring parameters from logs/model.ckpt-102015
INFO 2018-04-24 09:37:51.000064: tf_logging.py: 116 Restoring parameters from logs/model.ckpt-102015
INFO:tensorflow:Running local_init_op.
INFO 2018-04-24 09:37:51.000859: tf_logging.py: 116 Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO 2018-04-24 09:37:51.000911: tf_logging.py: 116 Done running local_init_op.
徘░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░`

图像里的字符是：簇paSvH哄7徘

我也试了别的图像，都只预测出最后一个，不知道哪里出了问题
这是参数
`--batch_size=1 --checkpoint=logs/model.ckpt-102015 --image_path_pattern=C:\Elag\data\cn_ocr\train\31c768fe-444d-11e8-9e87-005056bed121.jpg --dataset_name=newtextdataset`

期待回复

**Comment by A-bone1** [comment]
不好意思，这两天在外面浪没注意关注问题，你有试着在tensorboard中看一下损失函数和图片及对应的文本吗，是不是生成数据时标注标签时出错了呢

**Comment by A-bone1** [comment]
不好意思，这两天在外面浪没注意关注问题，你有试着在tensorboard中看一下损失函数和图片及对应的文本吗，是不是生成数据时标注标签时出错了呢

**Comment by ElagJun** [comment]
@A-bone1 非常感谢耐心的解答问题，正如你所说的一样，谢谢了 ，我在重新生成一遍

**Comment by gydlcc** [comment]
@ElagJun 　我想请问一下你的数据是怎么生成的呢
